#!/usr/bin/env /bin/bash
#
# __author__ = 'Lilian BESSON'
# __email__ = 'Lilian.BESSON[AT]ens-cachan[DOT]fr'
# __date__ = '18-12-2013'
#
# A small wrapper around the output of ocaml.
# Can be save to ~/bin/iocaml for example.
#
version='0.1'
LANG='en'

# Détection initiale: à adapter.
#ocaml=`whereis ocaml | grep -o "/[a-zA-Z/]*bin[a-zA-Z/]*ocaml" | head -n1`
#visual="$PAGER"

# Interpréteur ocaml à utiliser (changer si non standard)
# par exemple 4.0 installé ailleurs que le 3.12
ocaml="/usr/local/bin/ocaml graphics.cma"

# Pager à utiliser (peut être less, nano, pygmentize, emacs, vi ou ...)
visual="/home/lilian/.local/bin/NANO -v -Y ocaml"
# visual="pygmentize -l ocaml" 
# visual="less -r"

# Destinations (à changer si conflit)
ml="/tmp/iocaml.ml"
log="/tmp/iocaml.log"

for i in $@; do
	echo -e "(** iOCaml copy '$i' from '`pwd -P`' *)" | tee "$ml"
	cat "$i" >> "$ml"
	echo -e "(** iOCaml on ${i}:1:1 from '`pwd -P`' *)" | tee "$log"
	$ocaml < "$i" 2>&1 | tee -a $log | sed s{//toplevel//{"$i"{
	$visual "$log"
#	 | pygmentize -l ocaml -P encoding=`file -b --mime-encoding "$i"`
done

# END