#!/bin/bash
#
# Script by Lilian Besson
# http://besson.qc.to/

xtitle "(`date`<$USER@$HOSTNAME>:[`pwd`]> { Mutt 1.5.21 } : for ens-cachan.fr"

clear

/usr/bin/mutt-patched -F ~/.mutt/muttrc.ens "$@" && clear

rm -vf yes